apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmox-plugin-postman-newman-ci
  labels:
    app: cmox-plugin-postman-newman-ci
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cmox-plugin-postman-newman-ci
  template:
    metadata:
      labels:
        app: cmox-plugin-postman-newman-ci
    spec:
      containers:
      - name: plugin
        image: cmox/plugin-postman-newman-ci:1.7.0
        ports:
        - containerPort: 7890
        livenessProbe:
          httpGet:
            path: /health
            port: 7890
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cmox-plugin-postman-newman-ci-svc
spec:
  selector:
    app: cmox-plugin-postman-newman-ci
  ports:
  - port: 7890
    targetPort: 7890
